sonar.projectKey=Bloodborne2_ProjetoQA
sonar.projectName=ProjetoQA
sonar.projectVersion=0.0.1

sonar.organization=bloodborne2
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.qualitygate.wait=true
sonar.host.url=https://sonarcloud.io
