spring.application.name=ProjetoQA
spring.mongodb.uri=mongodb://localhost:27017/biblioteca_pessoal
spring.data.mongodb.auto-index-creation=true

spring.thymeleaf.cache=false
server.servlet.session.timeout=30m